### ISSUE TITLE
Should check if parent exists

### ISSUE THREAD

**Issue by tinovyatkin** [Rahul9046/eslint-plugin-good-practices#37]
```
$ eslint "{server,shared,data,src/scripts}/**/*.{js,mjs,es6,babel}" --ignore-pattern "*test*" --ignore-path .gitignore
TypeError: Cannot read property 'key' of null
Occurred while linting /Users/tino/Repos/engine/data/helpers/airlines.js:1
    at getParentFunctionName (/Users/tino/Repos/engine/node_modules/eslint-plugin-good-practices/rules/no-function-dependency.js:26:47)
    at checkInGivenParentScope (/Users/tino/Repos/engine/node_modules/eslint-plugin-good-practices/rules/no-function-dependency.js:47:37)
    at functionScopes.forEach (/Users/tino/Repos/engine/node_modules/eslint-plugin-good-practices/rules/no-function-dependency.js:78:35)
    at Array.forEach (<anonymous>)
    at checkDependency (/Users/tino/Repos/engine/node_modules/eslint-plugin-good-practices/rules/no-function-dependency.js:70:32)
    at Program:exit (/Users/tino/Repos/engine/node_modules/eslint-plugin-good-practices/rules/no-function-dependency.js:113:21)
    at listeners.(anonymous function).forEach.listener (/Users/tino/Repos/engine/node_modules/eslint/lib/util/safe-emitter.js:45:58)
    at Array.forEach (<anonymous>)
    at Object.emit (/Users/tino/Repos/engine/node_modules/eslint/lib/util/safe-emitter.js:45:38)
    at NodeEventGenerator.applySelector (/Users/tino/Repos/engine/node_modules/eslint/lib/util/node-event-generator.js:251:26)
error Command failed with exit code 2.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by Rahul9046** [comment]
@tinovyatkin , thanks for the feedback. Sorry for late reply. Will look into this issue asap
